config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('core.urls', namespace="core")),
    path("users/", include('users.urls', namespace="users")),
    path("rooms/", include('rooms.urls', namespace="rooms")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from .views import RoomDetail, SearchView

app_name = "rooms"

urlpatterns = [
    path('<int:pk>', RoomDetail.as_view(), name="room_detail"),
    path('search/', SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from .views import LoginView, log_out, SignupView

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", log_out, name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from core import models as core_models
from users import models as user_models
from django_countries.fields import CountryField
# Create your models here.


class AbstractItem(core_models.TimeStampedModel):
    """ Abstcract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """ RoomType Object Defination """

    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstractItem):

    """ Amenity Object Defination """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """ Facility Object Definatin """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """ HouseRule Object Defination """

    class Meta:
        verbose_name = "House Rule"


class Room(core_models.TimeStampedModel):
    """ Room Model Defination """

    name = models.CharField(max_length=150)
    description = models.TextField()
    country = CountryField(null=True)
    city = models.CharField(max_length=50)
    price = models.IntegerField()
    address = models.CharField(max_length=30)
    guests = models.IntegerField(help_text="How many people will be stay")
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        user_models.User, related_name="rooms", on_delete=models.CASCADE)
    room_type = models.ForeignKey(
        RoomType, related_name="rooms", on_delete=models.SET_NULL, null=True)
    aminities = models.ManyToManyField(
        Amenity, related_name="rooms", blank=True)
    facility = models.ManyToManyField(
        Facility, related_name="rooms", blank=True)
    house_rules = models.ManyToManyField(
        HouseRule, related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        # Call the real save() method
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        # from django.core.urlresolvers import reverse
        # return reverse('', kwargs={'pk': self.pk})
        return reverse('rooms:room_detail', kwargs={'pk': self.pk})

    def total_rating(self):
        all_review = self.reviews.all()
        all_rating = 0
        if len(all_review) > 0:
            for review in all_review:
                all_rating += review.rating_average()
            return all_rating / len(all_review)
        return 0

    def first_photo(self):
        photo, = self.photos.all()[:1]
        print(photo.file.url)
        return photo.file.url
        # print(self.photos.all())


class Photo(core_models.TimeStampedModel):

    """ Photo Model Defination """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="Rooms_Image")
    room = models.ForeignKey(
        Room, related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from .models import Room, RoomType, Amenity, Facility


class SearchForm(forms.Form):
    city = forms.CharField()
    country = CountryField(default="IN").formfield()
    price = forms.IntegerField(required=False)
    room_type = forms.ModelChoiceField(
        required=False, queryset=RoomType.objects.all())
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    aminities = forms.ModelMultipleChoiceField(
        queryset=Amenity.objects.all(), widget=forms.CheckboxSelectMultiple)
    facility = forms.ModelMultipleChoiceField(
        queryset=Facility.objects.all(), widget=forms.CheckboxSelectMultiple)

rooms/views.py
from django.views.generic import ListView, View
from django.views.generic.detail import DetailView
from django.shortcuts import render
from django_countries import countries
from django.core.paginator import Paginator
from .models import Room, RoomType, Amenity, Facility
from .forms import SearchForm


class HomeView(ListView):
    model = Room
    paginate_by = 10
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"
    template_name = "rooms/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["now"] = timezone.now
        return context

    def get_absolute_url(self):
        # form django.core.urlresolvers import reverse
        # return reverse('', kwargs={'pk': self.pk})
        return '/potato'


class RoomDetail(DetailView):
    model = Room
    context_object_name = "room"
    template_name = 'rooms/room_detail.html'


class SearchView(View):
    def get(self, request):
        form = SearchForm(request.POST)
        if form.is_valid():
            city = form.cleaned_data.get("city")
            country = form.cleaned_data.get("country")
            price = form.cleaned_data.get("price")
            room_type = form.cleaned_data.get("room_type")
            price = form.cleaned_data.get("price")
            guests = form.cleaned_data.get("guests")
            beds = form.cleaned_data.get("beds")
            bedrooms = form.cleaned_data.get("bedrooms")
            baths = form.cleaned_data.get("baths")
            instant_book = form.cleaned_data.get("instant_book")
            superhost = form.cleaned_data.get("superhost")
            aminities = form.cleaned_data.get("aminities")
            facility = form.cleaned_data.get("facility")

            filter_args = {}

            if city != "Anywhere":
                filter_args["city__startswith"] = city

            filter_args["country"] = country

            if room_type is not None:
                filter_args["room_type"] = room_type

            if price is not None:
                filter_args["price__lte"] = price

            if guests is not None:
                filter_args["guests__gte"] = guests

            if bedrooms is not None:
                filter_args["bedrooms__gte"] = bedrooms

            if beds is not None:
                filter_args["beds__gte"] = beds

            if baths is not None:
                filter_args["baths__gte"] = baths

            if instant_book is True:
                filter_args["instant_book"] = True

            if superhost is True:
                filter_args["host__superhost"] = True

            for amenity in amenities:
                filter_args["amenities"] = amenity

            for facility in facilities:
                filter_args["facilities"] = facility

            qs = Room.objects.filter(**filter_args)
            paginator = Paginator(qs, 10, orphans=5)
            page = request.GET.get("page", 1)
            rooms = paginator.get_page(page)
            return render(request, 'rooms/search.html', context={"rooms": rooms})
        else:
            form = SearchForm()
        return render(request, 'rooms/search.html', context={"form": form})

rooms/templates/partials/footer.html
<footer class="container justify-content-center text-center pb-5">
    &copy; 2020 Airbnb, Inc. All rights reserved
</footer>

rooms/templates/partials/github_login.html
<a href="" class="w-100 font-weight-light text-white bg-dark border border-secondary text-center my-2 py-2"
    style="border-radius:4px">
    <i class="fa fa-github mr-2 fa-lg"></i>Continue with Github
</a>

rooms/templates/partials/header.html
{% load static %}
<ul class="d-flex align-items-center text-sm font-weight-bold list-inline">
    {% if user.is_authenticated %}
    <li class="ml-4"><a href="{% url 'users:logout' %}">Log Out</a></li>
    {% else %}
    <li class="ml-4"><a href="{% url 'users:login' %}">Log In</a></li>
    <li class="ml-4"><a href="{% url 'users:signup' %}">Signup </a></li>
    {% endif %}
</ul>

rooms/templates/partials/room_card.html
{% load static %}
<div class="w-25 mb-3 px-2">
    <a href="{% url 'rooms:room_detail' room.pk %}">
        <!-- <img src="{{ room.first_photo }}" />
        {{ room.name }}/${{room.price}} -->
        <div class="w-100 img-fluid mb-2"
            style="height: 200px;background-position: center; border-radius:10px; background-size: cover;background-image: url({{ room.first_photo }});">
        </div>
        <div class="d-flex justify-content-between mb-2">
            <div>
                {% if room.host.superhost %}
                <span class="text-uppercase font-weight-bold border border-dark rounded px-1 py-1 mr-1">superhost</span>
                {% endif %}

                {{ room.city }}
                <!-- {{ room.country.flag}} -->
            </div>
            <span class="small" style="">
                <svg class="bi bi-star-fill mr-0.5 " width="1em" height="1em" viewBox="0 0 16 16"
                    fill="RGB(241, 245, 24)" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                </svg>
                {{ room.total_rating }}
            </span>
        </div>
        <span class="text-dark">{{room.name|truncatewords:7}}</span>
    </a>
</div>