config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('core.urls', namespace="core")),
    path("users/", include('users.urls', namespace="users")),
    path("rooms/", include('rooms.urls', namespace="rooms")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from .views import RoomDetail, SearchView

app_name = "rooms"

urlpatterns = [
    path('<int:pk>', RoomDetail.as_view(), name="room_detail"),
    path('search/', SearchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from core import models as core_models
from users import models as user_models
from django_countries.fields import CountryField
# Create your models here.


class AbstractItem(core_models.TimeStampedModel):
    """ Abstcract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """ RoomType Object Defination """

    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstractItem):

    """ Amenity Object Defination """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """ Facility Object Definatin """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """ HouseRule Object Defination """

    class Meta:
        verbose_name = "House Rule"


class Room(core_models.TimeStampedModel):
    """ Room Model Defination """

    name = models.CharField(max_length=150)
    description = models.TextField()
    country = CountryField(null=True)
    city = models.CharField(max_length=50)
    price = models.IntegerField()
    address = models.CharField(max_length=30)
    guests = models.IntegerField(help_text="How many people will be stay")
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        user_models.User, related_name="rooms", on_delete=models.CASCADE)
    room_type = models.ForeignKey(
        RoomType, related_name="rooms", on_delete=models.SET_NULL, null=True)
    aminities = models.ManyToManyField(
        Amenity, related_name="rooms", blank=True)
    facility = models.ManyToManyField(
        Facility, related_name="rooms", blank=True)
    house_rules = models.ManyToManyField(
        HouseRule, related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        # Call the real save() method
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        # from django.core.urlresolvers import reverse
        # return reverse('', kwargs={'pk': self.pk})
        return reverse('rooms:room_detail', kwargs={'pk': self.pk})

    def total_rating(self):
        all_review = self.reviews.all()
        all_rating = 0
        if len(all_review) > 0:
            for review in all_review:
                all_rating += review.rating_average()
            return all_rating / len(all_review)
        return 0

    def first_photo(self):
        photo, = self.photos.all()[:1]
        print(photo.file.url)
        return photo.file.url
        # print(self.photos.all())


class Photo(core_models.TimeStampedModel):

    """ Photo Model Defination """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="Rooms_Image")
    room = models.ForeignKey(
        Room, related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from .models import Room, RoomType, Amenity, Facility


class SearchForm(forms.Form):
    city = forms.CharField()
    country = CountryField(default="IN").formfield()
    price = forms.IntegerField(required=False)
    room_type = forms.ModelChoiceField(
        required=False, queryset=RoomType.objects.all())
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    aminities = forms.ModelMultipleChoiceField(
        queryset=Amenity.objects.all(), widget=forms.CheckboxSelectMultiple)
    facility = forms.ModelMultipleChoiceField(
        queryset=Facility.objects.all(), widget=forms.CheckboxSelectMultiple)

rooms/views.py
from django.views.generic import ListView, View
from django.views.generic.detail import DetailView
from django.shortcuts import render
from django_countries import countries
from django.core.paginator import Paginator
from .models import Room, RoomType, Amenity, Facility
from .forms import SearchForm


class HomeView(ListView):
    model = Room
    paginate_by = 10
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"
    template_name = "rooms/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["now"] = timezone.now
        return context

    def get_absolute_url(self):
        # form django.core.urlresolvers import reverse
        # return reverse('', kwargs={'pk': self.pk})
        return '/potato'


class RoomDetail(DetailView):
    model = Room
    context_object_name = "room"
    template_name = 'rooms/room_detail.html'


class SearchView(View):
    def get(self, request):
        form = SearchForm(request.POST)
        if form.is_valid():
            city = form.cleaned_data.get("city")
            country = form.cleaned_data.get("country")
            price = form.cleaned_data.get("price")
            room_type = form.cleaned_data.get("room_type")
            price = form.cleaned_data.get("price")
            guests = form.cleaned_data.get("guests")
            beds = form.cleaned_data.get("beds")
            bedrooms = form.cleaned_data.get("bedrooms")
            baths = form.cleaned_data.get("baths")
            instant_book = form.cleaned_data.get("instant_book")
            superhost = form.cleaned_data.get("superhost")
            aminities = form.cleaned_data.get("aminities")
            facility = form.cleaned_data.get("facility")

            filter_args = {}

            if city != "Anywhere":
                filter_args["city__startswith"] = city

            filter_args["country"] = country

            if room_type is not None:
                filter_args["room_type"] = room_type

            if price is not None:
                filter_args["price__lte"] = price

            if guests is not None:
                filter_args["guests__gte"] = guests

            if bedrooms is not None:
                filter_args["bedrooms__gte"] = bedrooms

            if beds is not None:
                filter_args["beds__gte"] = beds

            if baths is not None:
                filter_args["baths__gte"] = baths

            if instant_book is True:
                filter_args["instant_book"] = True

            if superhost is True:
                filter_args["host__superhost"] = True

            for amenity in amenities:
                filter_args["amenities"] = amenity

            for facility in facilities:
                filter_args["facilities"] = facility

            qs = Room.objects.filter(**filter_args)
            paginator = Paginator(qs, 10, orphans=5)
            page = request.GET.get("page", 1)
            rooms = paginator.get_page(page)
            return render(request, 'rooms/search.html', context={"rooms": rooms})
        else:
            form = SearchForm()
        return render(request, 'rooms/search.html', context={"form": form})

rooms/templates/rooms/home.html
{% extends "base.html" %}
{% load static %}


{% block page_title %}Home{% endblock %}

{% block content %}
<div class="container">
    <div class="mt-5 mb-5"
        style="height: 350px;background-color: #20202be5; border-radius:15px;background-repeat: no-repeat; background-size: cover;background-position: center;
    background-image: url(https://images.unsplash.com/photo-1551514716-ecf5d56078ed?ixlib=rb-1.2.1&auto=format&fit=crop&w=749&q=80);">

    </div>
    <div class="d-flex flex-wrap">
        {% for room in  rooms %}
        {% include "partials/room_card.html" with room=room %}
        {% endfor %}
    </div>
    <h3 class="text-center py-5 ">
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">previous</a>
        {% endif %}
        Page {{page_obj.number}} of {{ page_obj.paginator.num_pages }}
        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}">Next</a>
        {% endif %}
    </h3>
</div>

{% endblock %}

rooms/templates/rooms/room_detail.html
{% extends "base.html" %}
{% load static %}


{% block page_title %}Detail{% endblock page_title %}

{% block content %}
<div>
    <h1>
        {{ room.name }}
    </h1>
    <h3>
        {{ room.description }}
        {{ room.country }}
    </h3>
</div>
<div>
    <h2>
        By: {{ room.host.username }}
        {% if room.host.superhot %}
        (superhot)
        {% endif %}
    </h2>
    <h3>Amenities</h3>
    <ul>
        {% for aminity in room.aminities.all %}
        <li>{{aminity}}</li>
        {% endfor %}
    </ul>
    <h3>Facility</h3>
    <ul>
        {% for facility in room.facility.all %}
        <li>{{aminity}}</li>
        {% endfor %}
    </ul>
    <h3>House Rules</h3>
    <ul>
        {% for house_rule in room.house_rules.all %}
        <li>{{house_rule}}</li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

rooms/templates/rooms/search.html
{% extends "base.html" %}
{% load static %}


{% block page_title %}
Search
{% endblock %}

{% block search_bar %}
{% endblock search_bar %}

{% block content %}
<h1>Search!</h1>
<form method="GET" action="{% url 'rooms:search' %}">
    {{ form.as_p }}
    <button>Submit</button>
</form>
<h3>Result</h3>
{% for room in rooms %}
<h3>{{ room.name }}</h3>
{% endfor %}
{% endblock content %}

rooms/templates/rooms/search_odl.html
<div>
    <label for="city">City</label>
    <input value="{{city}}" id="city" name="city" type="text" placeholder="Search By City" />
</div>
<div>
    <label for="country">Country</label>
    <select name="country" id="country">
        {% for country in countries %}
        <option value="{{country.code}}" {% if country.code == s_country %}selected{% endif %}>
            {{ country.name }}</option>
        {% endfor %}
    </select>
</div>
<div>
    <label for="room_type">Country</label>
    <select name="room_type" id="room_type">
        <option value="0" {% if s_room_type == 0 %}selected{% endif %}>
            Room Type
        </option>
        {% for room_type in room_types %}
        <option value="{{room_type.pk}}" {% if s_room_type == room_type.pk %}selected{% endif %}>
            {{ room_type.name }}</option>
        {% endfor %}
    </select>
</div>
<div>
    <label for="price">Price</label>
    <input type="number" name="price" id="price" value={{ price }} placeholder="Price">
</div>
<div>
    <label for="guests">Guests</label>
    <input type="number" name="guests" id="guests" value={{ guests }} placeholder="Guets">
</div>
<div>
    <label for="bedrooms">Bedrooms</label>
    <input type="number" name="bedrooms" id="bedrooms" value={{ bedrooms }} placeholder="Bedrooms">
</div>
<div>
    <label for="beds">Beds</label>
    <input type="number" name="beds" id="beds" value={{ beds }} placeholder="Beds">
</div>
<div>
    <label for="baths">Baths</label>
    <input type="number" name="baths" id="baths" value={{ baths }} placeholder="Baths">
</div>
<div>
    <label for="instant">Instant Book Instant</label>
    <input type="checkbox" name="instant" id="instant" {% if instant %} checked {% endif %}>
</div>
<div>
    <label for="super_host">By Super Host Only</label>
    <input type="checkbox" name="super_host" id="super_host" {% if super_host %} checked {% endif %}>
</div>
<div>
    <h3>Amenities</h3>
    <ul>
        {% for amenity in amenities %}
        <li>
            <label for="a_{{amenity.pk}}">{{ amenity.name }}</label>
            <input type="checkbox" name="amenity" id="a_{{amenity.pk}}" value="{{amenity.pk}}"
                {% if amenity.pk|slugify in s_amenities %} checked {% endif %}>
        </li>
        {% endfor %}
    </ul>
</div>
<div>
    <h3>Facilities</h3>
    <ul>
        {% for facility in facilities %}
        <li>
            <label for="a_{{facility.pk}}">{{ facility.name }}</label>
            <input type="checkbox" name="facility" id="{{facility.pk}}" value="{{facility.pk}}"
                {% if facility.pk|slugify in s_facilities %} checked {% endif %}>
        </li>
        {% endfor %}
    </ul>
</div>
<button>Submit</button>